package budowa;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import domena.Byt;
import domena.Loginy;
import mapery.MapujDoBytu;
import repozytoria.RepLoginy;
import repozytoria.Strony;
import uow.UnitOfWork;

public class RepoLoginow extends BazaRepo<Loginy> implements RepLoginy{

	public RepoLoginow(Connection polaczenie, MapujDoBytu<Loginy> mapper, UnitOfWork uow) {
		super(polaczenie, mapper, uow);
	}

	public void persistAdd(Byt entity) {
		try {
			setUpInsert((Byt)entity);
			insert.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	@Override
	protected String getTableName() {
		return "t_sys_users";
	}

	@Override
	protected String getCreateTableQuery() {
		return "CREATE TABLE t_sys_users ("
         		+ "id INT GENERATED BY DEFAULT AS IDENTITY, "
         		+ "login VARCHAR(255) NOT NULL, "
         		+ "haslo VARCHAR(255) NOT NULL, "
         		+ "PRIMARY KEY (id));";
	}

	@Override
	protected String getInsertQuery() {
		return "INSERT INTO T_SYS_USERS ( ID, LOGIN, HASLO ) VALUES ( ?, ?, ?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "UPDATE t_sys_users SET (id, login, haslo)=(?,?,?) WHERE id=?";
	}

	@Override
	protected void setUpInsert(Byt byt) throws SQLException {
		Loginy user = (Loginy)byt;
			insert.setLong(1, user.getId());
			insert.setString(2, user.getLogin());
			insert.setString(3, user.getHaslo());
	}

	@Override
	protected void setUpUpdate(Byt byt) throws SQLException {
		Loginy user = (Loginy)byt;
		update.setString(1, user.getLogin());
		update.setString(2, user.getHaslo());
		
	}

	public void count() {
	}

	public void modify(Loginy byt) {
	}

	public void allOnPage(Strony strona) {		
	}

	public Loginy withId(long id) {
		return null;
	}

	public List<Loginy> withLogin(String login) {
		return null;
	}

	public List<Loginy> withLoginAndPassword(String login, String haslo) {
		return null;
	}

	public void setupPermissions(Loginy login) {
		
	}

	public void trwaleDodanie(Byt byt) {
		
	}

	public void trwalaZmiana(Byt byt) {
		
	}

	public void trwaleUsun(Byt byt) {
		
	}

	public List<Loginy> zL(String Login) {
		return null;
	}

	public List<Loginy> zLiH(String Login, String Haslo) {
		return null;
	}

	public void ustawUprawnienie(Loginy Login) {
		
	}

}